### ISSUE TITLE
[Bug]: Jellyfin not initializing

### ISSUE THREAD

**Issue by taehas** [Ashu11-A/Ashu_eggs#11] opened 2024-07-26 12:47 UTC
### Panel Version

1.11.7

### Wings Version

1.11.7

### Service

Jellyfin

### Modified

No, I did not modify the egg

### Expected Behavior

Step 1 : Install Egg
Step 2: Functions as normal

### Actual Behavior

Step 1: Install Egg 
Step 2: Crashes 
![Screenshot 2024-07-26 143652](https://github.com/user-attachments/assets/336a24d0-a418-4448-8444-2d1f4ef39b69)

### Steps To Reproduce

Install as normal, seems to have not create several folders/ not have access to them.

### Install logs

https://pteropaste.com/s3z5/

**Comment by Ashu11-A** [comment] 2024-07-26 18:15
Permission error, they probably changed the way Jellyfin is configured, as I had to do a Reverse Proxy on it, as the port couldn't be set, if I'm not mistaken

**Comment by Ashu11-A** [comment] 2024-07-26 18:25
hmm, it looks like there's something wrong with your installation, since even Nginx didn't start up due to a lack of permissions
| Terminal | APP |
|--|--|
| ![image](https://github.com/user-attachments/assets/906fd1d3-9160-4cfd-84d3-64494eb40f91) | ![image](https://github.com/user-attachments/assets/b8916512-7d78-4eb1-bf31-80610b8a708a) |

try reinstalling, if you still get an error, I'll look into it further

**Comment by taehas** [comment] 2024-07-27 12:25
<img width="868" alt="Screenshot 2024-07-27 at 2 24 13 PM" src="https://github.com/user-attachments/assets/7705a9b5-6ca0-4e8a-be36-9fd5368058c0">

Fresh install, it did this the first few times I tried installing before reporting too.

**Comment by Ashu11-A** [comment] 2024-07-27 19:11
oh

**Comment by Ashu11-A** [comment] 2024-07-27 19:13
can you send me the installation log?

**Comment by taehas** [comment] 2024-07-28 11:57
Here you go https://pteropaste.com/xjcp/

**Comment by Ashu11-A** [comment] 2024-07-30 00:50
> Here you go https://pteropaste.com/xjcp/

This doesn't seem to be egg's initialization when it starts installing, where is this log from?

**Comment by Ashu11-A** [comment] 2024-07-30 00:57
Everything looks fine to me, but there are parts of the log missing, but I think it's fine

I'm going to research the problem, as I can't reproduce it in any way

**Comment by Ashu11-A** [comment] 2024-07-30 01:18
Fixed in [#391003d](https://github.com/Ashu11-A/Ashu_eggs/commit/391003d23dc2058918d07cf2f08af8a11c193a0e)

If it shows up again, let me know, but I believe this has been solved, I'm setting the permissions to “777” (allowing ALL users read/write/execute permissions), I think this is a special case, since I couldn't reproduce it, if possible, let me know the:

kernel version of the machine:
```sh
uname -r
```

version of your Docker running:
```sh
docker --version
```

**Comment by Ashu11-A** [comment] 2024-07-30 01:20
If you could test other “Eggs” to see if this happens again, I'd appreciate it!

**Comment by taehas** [comment] 2024-07-30 14:58
<img width="874" alt="Screenshot 2024-07-30 at 4 56 37 PM" src="https://github.com/user-attachments/assets/3c5daaeb-b950-4407-8b3c-bea2daf9a88e">

https://pteropaste.com/0qie

tried uninstalling and reinstalling, the script is on the right version.
kernel is 5.10.0-31-amd64
Docker version 27.1.1, build 6312585

**Comment by Ashu11-A** [comment] 2024-07-31 04:07
If possible contact me on Discord, my id: ashu11_a, I will ask you to give me access to your panel, a friend of mine tested it on an amd64 machine and it worked normally, your case is very special and I want to understand why the permissions are not properly defined

**Comment by taehas** [comment] 2024-08-06 12:43
> > <img alt="Screenshot 2024-07-30 at 4 56 37 PM" width="874" src="https://private-user-images.githubusercontent.com/71333576/353509077-3c5daaeb-b950-4407-8b3c-bea2daf9a88e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTMzNjgsIm5iZiI6MTcyMjQxMzA2OCwicGF0aCI6Ii83MTMzMzU3Ni8zNTM1MDkwNzctM2M1ZGFhZWItYjk1MC00NDA3LThiM2MtYmVhMmRhZjlhODhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA4MDQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmYmNmZjhhMWZiYWUzZjAxNTA0ZDFjMTk5Mjc0NGYzZmU3NWVlYjg2NmQwZmU5MGM1ZTRkYjYyYjc2YTFiYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fCf1p8FmGcLvM0eWRqutZQm_KOvu1aEg2GTPgMt3yNs">
> > https://pteropaste.com/0qie
> > tried uninstalling and reinstalling, the script is on the right version. kernel is 5.10.0-31-amd64 Docker version 27.1.1, build 6312585
> 
> What is your virtualization system? or is it a dedicated machine? use the command below to find out
> 
> ```shell
> systemd-detect-virt
> ```
> 
> if it doesn't return anything use
> 
> ```shell
> sudo dmidecode -s system-manufacturer
> ```

virt is none and manufacturer is supermicro

**Comment by Ashu11-A** [comment] 2024-08-08 18:04
Inconclusive result. The user claimed that other servers were also experiencing permission errors, and when installing as a regular user inside the Docker container, it worked 'normally.' I believe something external was overwriting the file permissions for another user. The write permissions remained the same, but since the 'owner' of the folders was different, it was not possible to create, edit, or delete files. Even after setting the owner of the /home/container folder to 'container' or adding the user 'www-data', it was not possible to change the installation behavior. At one point, the folder owner was a certain [polkitd](https://en.wikipedia.org/wiki/Polkit), but I'm not sure if that can be considered relevant.

**Closed by Ashu11-A** 2024-08-08 18:04 UTC

**Comment by taehas** [comment] 2024-08-15 16:30
Found a fix for this issue, due to the Pterodactyl config.yml flag 
`check_permissions_on_boot` being set to false it could not properly configure permissions upon boot.
Simply set it to true and relaunch wings, and all should be functional.
